version: '2.2'
services:
  web:
    image: node-marmita
    build: docker/node 
    links:
      - db
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src
    cpus: "0.5"
    mem_limit: 512m
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=marmita
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=marmita
